---
# tasks file for my_git_role

- name: install packages
  ansible.builtin.package:
    name: "{{ git_packages }}"
    state: present

- name: place git configuration
  ansible.builtin.template:
    src: gitconfig.j2
    dest: /home/{{ machine_user_name }}/.gitconfig
    mode: "0644"
  when:
    - git_user_email is defined
    - git_user_name is defined
    - machine_user_name is defined
    # - git_username is defined
    # - getent_passwd[git_username] != none